server:
  port: 8080

spring:
  application:
    name: fake-detection
  datasource:
    url: jdbc:mysql://fake-detection-db.c3ey0w642aok.ap-northeast-2.rds.amazonaws.com:3306/fakeDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: aivle202406
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: none  # `create`, `update`, `validate`, `none` 중 선택
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: hops0210
    password: efxqcjbwxotahzmz
    properties:
      mail:
        smtp:
          auth: true            # 사용자 인증 시도 여부
          starttls:
            enable: true        # starttls 활성화 여부
  web:
    resources:
      static-locations: classpath:/static/
  devtools:
    livereload:
      enabled: true
    thymeleaf:
      cache: false
    restart:
      enabled: true
  cloud:
    openfeign:
      httpclient:
        connection-timeout: 120000
        ok-http:
          read-timeout: 120s
logging:
  level:
    feign.client: DEBUG
    org:
      springframework:
        security: DEBUG
        web:
          filter: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
service:
  jwt:
    secret-key: 3nZ2u9bK0jLW5qPvX7oY6eR8JzF1TgD4cA3sQkUuIV8HnP1wLGzYjS

upload:
  path: src/main/resources/static/images/

cloud:
  aws:
    s3:
      bucket: fake-detecting-storage
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: AKIA2S2Y4FJI4EGVBKHT
      secretKey: aH0Ph49DFMU9hSPoqr5bo1+EOldk2thcsJMteNP7

payment:
    api:
      key: qTm6GDWqy2sFy0US9r7ojMICjWdstrnDSDGpL28UFSHJQxpDQI3VJEBT6FKvDnccFCUKBnn5nnePUOue