server:
  port: 8080

spring:
  application:
    name: fake-detection
  profiles:
    activate: local
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    jpa:
      properties:
        default_batch_fetch_size: 100
      hibernate:
        format_sql: true
        use_sql_comments: true
        ddl-auto: update
      show-sql: true
#      database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enable: true
      path: /h2-console
  mail:
    host: smtp.gmail.com
    port: 587
    username: hops0210
    password: efxqcjbwxotahzmz
    properties:
      mail:
        smtp:
          auth: true            # 사용자 인증 시도 여부
          starttls:
            enable: true        # starttls 활성화 여부
  web:
    resources:
      static-locations: classpath:/static/
  devtools:
    livereload:
      enabled: true
    thymeleaf:
      cache: false
    restart:
      enabled: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
service:
  jwt:
    secret-key: 3nZ2u9bK0jLW5qPvX7oY6eR8JzF1TgD4cA3sQkUuIV8HnP1wLGzYjS

upload:
  path: src/main/resources/static/images/
