spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: hops0210
    password: efxqcjbwxotahzmz
    properties:
      mail:
        smtp:
          auth: true            # 사용자 인증 시도 여부
          starttls:
            enable: true        # starttls 활성화 여부