spring:
  datasource:
    url: jdbc:mysql://fake-detection-db.c3ey0w642aok.ap-northeast-2.rds.amazonaws.com:3306/fakeDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    url: jdbc:mysql://localhost:3306/fake
    username: root
    password: aivle202406
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: none  # `create`, `update`, `validate`, `none` 중 선택
    properties:
      hibernate:
        format_sql: true
    show-sql: true
cloud:
  aws:
    s3:
      bucket: fake-detecting-storage
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: AKIA2S2Y4FJI4EGVBKHT
      secretKey: aH0Ph49DFMU9hSPoqr5bo1+EOldk2thcsJMteNP7