server:
  port: 8080

spring:
  application:
    name: fake-detection
  mail:
    host: smtp.gmail.com
    port: 587
    username: hops0210
    password: efxqcjbwxotahzmz
    properties:
      mail:
        smtp:
          auth: true            # 사용자 인증 시도 여부
          starttls:
            enable: true        # starttls 활성화 여부
  web:
    resources:
      static-locations: classpath:/static/
  devtools:
    livereload:
      enabled: true
    thymeleaf:
      cache: false
    restart:
      enabled: true
  cloud:
    openfeign:
      httpclient:
        connection-timeout: 120000
        ok-http:
          read-timeout: 120s
logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          filter: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
service:
  jwt:
    secret-key: 3nZ2u9bK0jLW5qPvX7oY6eR8JzF1TgD4cA3sQkUuIV8HnP1wLGzYjS

upload:
  path: src/main/resources/static/images/
